version: '3.9'

services:
    postgres:
        container_name: pg-db_e
        image: postgres
        environment:
            POSTGRES_USER: e-com
            POSTGRES_PASSWORD: e-com@1234
            POSTGRES_DB: e-com
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data
        networks:
            - default
    pg-admin:
        container_name: pg_admin_e
        image: dpage/pgadmin4:8
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@email.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 5050
        ports:
            - 5051:5050
        volumes:
            - ./pgadmin_data:/data/db
        depends_on:
            - postgres
        networks:
            - default
    redis:
        image: redis:6.0.7
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - ./redis_data:/data
        networks:
            - default
    redis_insight:
        image: redislabs/redisinsight:1.14.0
        container_name: redis_insight
        ports:
            - 8001:8001
        volumes:
            - ./redis_insight_data:/db
        depends_on:
            - redis
        networks:
            - default
volumes:
    pg_data:
        driver: 'local'
    redis_data:
        driver: 'local'
    redis_insight_data:
        driver: 'local'
networks:
  spring-demo:
    driver: 'bridge'
  default:
    driver: 'bridge'
